[pin]
height = 32
width = 48
spacing = 40

# width of the IN/OUT triangles on pins
width_direction = 16

# enable/disable colors on pins
color_enabled = 1

# color aliases
[pin.colors]
default = "#ffffff"
ADDR    = "#ffd700"
ADDR2   = "#ffa500"
ADDR3   = "#ff6347"
CLOCK   = "#ffc0cb"
DATA    = "#00ced1"
DATA2   = "#5f9ea0"
DATA3   = "#4682b4"
EN      = "#ff1493"
GND     = "#32cd32"
MISC    = "#ee82ee"
NC      = "#d3d3d3"
POWER   = "#ff0000"

# DIP specific settings
[package.dip]
side_pad = 160
top_pad = 40

# DIP package width aliases
[package.dip.width]
default = 220
SKINNY  = 114
WIDE    = 340

# Edge Connector specific settings
[package.edge]
side_pad = 300
top_pad  = 40

# PLCC specific settings
[package.plcc]
side_pad = 160

# QFP specific settings
[package.qfp]
side_pad = 160

# SIP specific settings
[package.sip]
bottom_pad = 40